language: python
python:
  - "2.7"
cache: pip
env: DJ_KEY=testkey
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - cp test_settings.py settings.py
  - ./manage.py migrate
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
