language: python
python:
  - "2.7"
env: DJ_KEY=testkey
install:
  # - |
  #   echo "DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': 'travisdb'}}" > api/settings.py
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
script: 
  - cp test_settings.py settings.py
  - ./manage.py migrate
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
